name: 'Rust AWS Lambda'
description: 'Generates AWS Lambda compatible packages for all your Rust binaries'
branding:
  icon: 'package'  
  color: 'orange'

inputs:
  source-dir:
    description: 'The relative path to the folder where Cargo.toml is placed'
    required: true
    default: '.'

runs:
  using: 'docker'
  image: 'docker://miere/action-rust-aws-lambda:1.51.0'
  args:
    - ${{ inputs.source-dir }}
  env:
    PROFILE: "release"
    PACKAGE: "true"
